apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  selector:
    app: vllm-gpu
  ports:
  - protocol: TCP
    port: 11436               # Port on the Service
    targetPort: 8000         # Port on the Pod
    nodePort: 30300
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-gpu
      version: v01
  template:
    metadata:
      labels:
        app: vllm-gpu
        version: v01
    spec:
      containers:
      - name: vllm-gpu
        image: vllm/vllm-openai:latest
        securityContext:
          runAsUser: 0  # Use 0 for root user
          runAsGroup: 0 # Use 0 for root group
            #          privileged: true # This setting might be necessary for some actions
        command: ["/bin/bash"]
        args: ["-c", "trap : TERM INT; sleep infinity & wait"]
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8000
        env:
        - name: VLLM_PORT
          value: "8000"
        volumeMounts:
          - name: nfs-volume
            mountPath: /root/.cache/huggingface
      volumes:
        - name: nfs-volume
          nfs:
            server: nfs_server # server hostname or ip
            path: /data/huggingface
            readOnly: no
